version: '3'
services:
  anaconda:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: anaconda
    command: /bin/bash
    ports:
      - "8888:8888"
    tty: true
    volumes:
      - ./Project:/code