version: '2.3'
services:
  tensorflow-gpu:
    build:
      dockerfile: Dockerfile
    container_name: anaconda
    command: /bin/bash
    ports:
      - "8000:8888"
    tty: true
    volumes:
      - ./Project:/code